version: "3.8"
services:
  q-gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    container_name: q-gateway
    ports:
      - "8081:8081"
    environment:
      - HTTP_PORT=8081
      - QTTY_PORT=7682
      - SOP_DIR=/app/sop
      - TASK_DOC_PATH=/app/task_instructions.md
      - TASK_DOC_BUDGET=131072
    volumes:
      - ../q-sessions:/srv/q-sessions
      - ../bin/q:/usr/local/bin/q:ro
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 512M


